networks:
    base-network:
        driver:
            bridge
services:
    ###> doctrine/doctrine-bundle ###
    database:
        image: mysql:8.0
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 'addmin'
            MYSQL_DATABASE: 'app'
            MYSQL_USER: 'user'
            MYSQL_PASSWORD: 'pass'
        ports:
            - "3310:3306"
        networks:
            - base-network

    app:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        restart: always
        container_name: app-banque-container
        volumes:
            - ./:/var/www/html
            - symfony_var:/var/www/html/var
            - symfony_vendor:/var/www/html/vendor
        ports:
            - "8085:80"
        entrypoint: [ "/usr/local/bin/entrypoint.sh" ]
        command: [ "apache2-foreground" ]
        environment:
            DATABASE_URL: "mysql://root:addmin@database:3306/app?serverVersion=8.0.43&charset=utf8mb4"
        networks:
            - base-network

volumes:
    symfony_var:
    symfony_vendor:
